services:
  database:
    image: postgres
    container_name: shoppy_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shoppydb
    volumes:
      - postgres_vol:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - pgadmin_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: shoppy_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_vol:/var/lib/pgadmin
    networks:
      - pgadmin_network
    ports:
      - "5050:80"
    depends_on:
      - database
    restart: unless-stopped

networks:
  pgadmin_network:
    driver: bridge

volumes:
  postgres_vol:
  pgadmin_vol: